<?php

/** @noinspection GlobalVariableUsageInspection */
/** @noinspection SpellCheckingInspection */
/** @noinspection MethodVisibilityInspection */

namespace Dotlines\Ghoori\Tests;

use Dotenv\Dotenv;
use Dotlines\Ghoori\AccessTokenRequest;
use Exception;
use GuzzleHttp\Exception\ClientException;
use JsonException;
use PHPUnit\Framework\TestCase;

class AccessTokenRequestTest extends TestCase
{
    protected $backupStaticAttributes = false;
    protected $runTestInSeparateProcess = false;

    public string $tokenUrl = '';
    public string $username = '';
    public string $password = '';
    public int $clientID = 0;
    public string $clientSecret = '';

    final public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Dotenv::createImmutable(__DIR__ . '\\..')->load();

        $this->tokenUrl = array_key_exists('GHOORI_TOKEN_URL', $_ENV) ? (string)$_ENV['GHOORI_TOKEN_URL'] : (string)getenv('GHOORI_TOKEN_URL');
        $this->username = array_key_exists('GHOORI_USERNAME', $_ENV) ? (string)$_ENV['GHOORI_USERNAME'] : (string)getenv('GHOORI_USERNAME');
        $this->password = array_key_exists('GHOORI_PASSWORD', $_ENV) ? (string)$_ENV['GHOORI_PASSWORD'] : (string)getenv('GHOORI_PASSWORD');
        $this->clientID = array_key_exists('GHOORI_CLIENT_ID', $_ENV) ? (int)$_ENV['GHOORI_CLIENT_ID'] : (int)getenv('GHOORI_CLIENT_ID');
        $this->clientSecret = array_key_exists('GHOORI_CLIENT_SECRET', $_ENV) ? (string)$_ENV['GHOORI_CLIENT_SECRET'] : (string)getenv('GHOORI_CLIENT_SECRET');
    }

    /** @test
     * @throws JsonException
     */
    final public function it_can_fetch_access_token(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, $this->clientID, $this->clientSecret);
        $tokenResponse = $accessTokenRequest->send();

        self::assertNotEmpty($tokenResponse);
        self::assertArrayHasKey('token_type', $tokenResponse);
        self::assertArrayHasKey('expires_in', $tokenResponse);
        self::assertArrayHasKey('access_token', $tokenResponse);
        self::assertArrayHasKey('refresh_token', $tokenResponse);
        self::assertNotEmpty($tokenResponse['token_type']);
        self::assertNotEmpty($tokenResponse['expires_in']);
        self::assertNotEmpty($tokenResponse['access_token']);
        self::assertNotEmpty($tokenResponse['refresh_token']);
    }


    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_empty_url(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance("", $this->username, $this->password, $this->clientID, $this->clientSecret);
        $this->expectException(Exception::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_wrong_url(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance("https://sb-payments.ghoori.com.bd/oauth", $this->username, $this->password, $this->clientID, $this->clientSecret);
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_empty_username(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, "", $this->password, $this->clientID, $this->clientSecret);
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_wrong_username(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, "wronguser", $this->password, $this->clientID, $this->clientSecret);
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */

    final public function it_gets_exception_with_empty_password(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, "", $this->clientID, $this->clientSecret);
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */

    final public function it_gets_exception_with_wrong_password(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, "wrongpassword", $this->clientID, $this->clientSecret);
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */

    final public function it_gets_exception_with_empty_client_secret(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, $this->clientID, "");
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */

    final public function it_gets_exception_with_wrong_client_secret(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, $this->clientID, "wrongclientsecret");
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }


    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_negative_client_id(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, -27, $this->clientSecret);
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_wrong_client_id(): void
    {
        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, 99999, $this->clientSecret);
        $this->expectException(ClientException::class);
        $accessTokenRequest->send();
    }
}
