<?php

/** @noinspection GlobalVariableUsageInspection */
/** @noinspection SpellCheckingInspection */
/** @noinspection MethodVisibilityInspection */

namespace Dotlines\Ghoori\Tests;

use Dotenv\Dotenv;
use Dotlines\Ghoori\AccessTokenRequest;
use Dotlines\Ghoori\RefreshTokenRequest;
use Exception;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\ConnectException;
use JsonException;
use PHPUnit\Framework\TestCase;

class RefreshTokenRequestTest extends TestCase
{
    protected $backupStaticAttributes = false;
    protected $runTestInSeparateProcess = false;

    public string $tokenUrl = '';
    public string $username = '';
    public string $password = '';
    public int $clientID = 0;
    public string $clientSecret = '';

    public string $accessToken = "";
    public string $refreshToken = "";

    /**
     * @throws JsonException
     */
    final public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Dotenv::createImmutable(__DIR__ . '\\..')->safeLoad();

        $this->tokenUrl = (array_key_exists('GHOORI_SERVER_URL', $_ENV) ? (string)$_ENV['GHOORI_SERVER_URL'] : (string)getenv('GHOORI_SERVER_URL')) . '/oauth/token';
        $this->username = array_key_exists('GHOORI_USERNAME', $_ENV) ? (string)$_ENV['GHOORI_USERNAME'] : (string)getenv('GHOORI_USERNAME');
        $this->password = array_key_exists('GHOORI_PASSWORD', $_ENV) ? (string)$_ENV['GHOORI_PASSWORD'] : (string)getenv('GHOORI_PASSWORD');
        $this->clientID = array_key_exists('GHOORI_CLIENT_ID', $_ENV) ? (int)$_ENV['GHOORI_CLIENT_ID'] : (int)getenv('GHOORI_CLIENT_ID');
        $this->clientSecret = array_key_exists('GHOORI_CLIENT_SECRET', $_ENV) ? (string)$_ENV['GHOORI_CLIENT_SECRET'] : (string)getenv('GHOORI_CLIENT_SECRET');

        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, $this->clientID, $this->clientSecret);
        $tokenResponse = $accessTokenRequest->send();

        $this->accessToken = (string)$tokenResponse['access_token'];
        $this->refreshToken = (string)$tokenResponse['refresh_token'];
    }

    /** @test
     * @throws JsonException
     */
    final public function it_can_refresh_access_token(): void
    {
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $refreshTokenResponse = $refreshTokenRequest->send();

        self::assertNotEmpty($refreshTokenResponse);
        self::assertArrayHasKey('token_type', $refreshTokenResponse);
        self::assertArrayHasKey('expires_in', $refreshTokenResponse);
        self::assertArrayHasKey('access_token', $refreshTokenResponse);
        self::assertArrayHasKey('refresh_token', $refreshTokenResponse);
    }

    /**
     * Testing $tokenUrl param
     */

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_empty_tokenUrl(): void
    {
        $this->tokenUrl = "";
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(Exception::class);
        $refreshTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_wrong_tokenUrl(): void
    {
        $this->tokenUrl = "sdasdadssad";
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(ConnectException::class);
        $refreshTokenRequest->send();
    }

    /**
     * Testing $clientID param
     */

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_clientID_zero(): void
    {
        $this->clientID = 0;
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(Exception::class);
        $refreshTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_negative_clientID(): void
    {
        $this->clientID = -27;
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(ClientException::class);
        $refreshTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_wrong_clientID(): void
    {
        $this->clientID = 9999999999;
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(ClientException::class);
        $refreshTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_large_clientID(): void
    {
        $this->clientID = 99999999999;
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(ClientException::class);
        $refreshTokenRequest->send();
    }

    /**
     * Testing $clientSecret param
     */

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_empty_clientSecret(): void
    {
        $this->clientSecret = "";
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(ClientException::class);
        $refreshTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_integer_clientSecret(): void
    {
        $this->clientSecret = "22";
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(ClientException::class);
        $refreshTokenRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_gets_exception_with_wrong_clientSecret(): void
    {
        $this->clientSecret = "sssssssssssssssssssssssssssssssssssssssss";
        $refreshTokenRequest = RefreshTokenRequest::getInstance($this->tokenUrl, $this->accessToken, $this->clientID, $this->clientSecret, $this->refreshToken);
        $this->expectException(ClientException::class);
        $refreshTokenRequest->send();
    }
}
