name: Tests

environment: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.4, 8.0]
        stability: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Create .env file
        run: |
          touch .env
          echo SERVER_URL=${SERVER_URL} >> .env
          echo USERNAME=${USERNAME} >> .env
          echo PASSWORD=${PASSWORD} >> .env
          echo CLIENT_ID=${CLIENT_ID} >> .env
          echo CLIENT_SECRET=${CLIENT_SECRET} >> .env
          cat .env

      - name: Execute tests
        run: vendor/bin/phpunit
